/* ============================================================================
 * TrustStore.cpp — persistent CA certificate store implementation
 * LGPL v3
 * Built only when NN_ENABLE_TRUST=ON
 * ============================================================================ */

#include <plugin-api/trust/TrustStore.h>

#include <openssl/bio.h>
#include <openssl/pem.h>
#include <openssl/x509.h>
#include <openssl/err.h>

#include <cstring>
#include <ctime>
#include <fstream>

// Embedded root CA public key (DER-encoded SubjectPublicKeyInfo, ECDSA P-256).
// Production builds: the CI pipeline replaces this placeholder with the real
// NNStudio root CA public key bytes at link time via --defsym / objcopy.
// Development builds: a test key generated by nnstudio-sign keygen is used.
static const unsigned char kRootCaPubKeyDer[] = {
    // PLACEHOLDER — replaced at build time; 91 bytes for P-256 SPKI
    0x30, 0x59, 0x30, 0x13, 0x06, 0x07, 0x2a, 0x86, 0x48, 0xce, 0x3d, 0x02,
    0x01, 0x06, 0x08, 0x2a, 0x86, 0x48, 0xce, 0x3d, 0x03, 0x01, 0x07, 0x03,
    0x42, 0x00, 0x04,
    // 64 bytes of placeholder public key (x || y coordinates)
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};
static const size_t kRootCaPubKeyDerLen = sizeof(kRootCaPubKeyDer);

namespace nnstudio {
namespace trust {

// ─── File I/O helpers ──────────────────────────────────────────────────────────
namespace {

Result<std::vector<uint8_t>> readFile(std::string_view path) {
    std::ifstream f(std::string{path}, std::ios::binary);
    if (!f.is_open()) return Result<std::vector<uint8_t>>{"TrustStore: cannot open file"};
    f.seekg(0, std::ios::end);
    auto sz = static_cast<size_t>(f.tellg());
    f.seekg(0, std::ios::beg);
    std::vector<uint8_t> data(sz);
    f.read(reinterpret_cast<char*>(data.data()), static_cast<std::streamsize>(sz));
    if (!f) return Result<std::vector<uint8_t>>{"TrustStore: read error"};
    return Result<std::vector<uint8_t>>{std::move(data)};
}

inline uint32_t readU32LE(const uint8_t* p) {
    return static_cast<uint32_t>(p[0])
         | static_cast<uint32_t>(p[1]) <<  8
         | static_cast<uint32_t>(p[2]) << 16
         | static_cast<uint32_t>(p[3]) << 24;
}

inline int64_t readI64LE(const uint8_t* p) {
    return static_cast<int64_t>(
        static_cast<uint64_t>(p[0])        | static_cast<uint64_t>(p[1]) <<  8 |
        static_cast<uint64_t>(p[2]) << 16  | static_cast<uint64_t>(p[3]) << 24 |
        static_cast<uint64_t>(p[4]) << 32  | static_cast<uint64_t>(p[5]) << 40 |
        static_cast<uint64_t>(p[6]) << 48  | static_cast<uint64_t>(p[7]) << 56);
}

inline void writeU32LE(uint8_t* p, uint32_t v) {
    p[0] = static_cast<uint8_t>(v);
    p[1] = static_cast<uint8_t>(v >>  8);
    p[2] = static_cast<uint8_t>(v >> 16);
    p[3] = static_cast<uint8_t>(v >> 24);
}

inline void writeI64LE(uint8_t* p, int64_t v) {
    auto u = static_cast<uint64_t>(v);
    for (int i = 0; i < 8; ++i) p[i] = static_cast<uint8_t>(u >> (i*8));
}

} // anonymous namespace

// ─── findByDN ─────────────────────────────────────────────────────────────────

const CaEntry* TrustStore::findByDN(std::string_view dn) const noexcept {
    for (const auto& e : entries_)
        if (e.subjectDN == dn) return &e;
    return nullptr;
}

// ─── addCa / revokeCa ─────────────────────────────────────────────────────────

Result<void> TrustStore::addCa(CaEntry entry) {
    if (entry.derCert.empty()) return Result<void>{"TrustStore::addCa: empty DER cert"};
    // De-duplicate by DN
    for (const auto& e : entries_)
        if (e.subjectDN == entry.subjectDN) return Result<void>{}; // already present
    entries_.push_back(std::move(entry));
    return Result<void>{};
}

Result<void> TrustStore::revokeCa(std::string_view dn) {
    for (auto it = entries_.begin(); it != entries_.end(); ++it) {
        if (it->subjectDN == dn) {
            entries_.erase(it);
            return Result<void>{};
        }
    }
    return Result<void>{"TrustStore::revokeCa: DN not found"};
}

// ─── load ─────────────────────────────────────────────────────────────────────

Result<void> TrustStore::load(std::string_view path) {
    auto fileR = readFile(path);
    if (!fileR.ok()) return Result<void>{fileR.error()};
    const auto& buf = fileR.value();

    // Parse header
    if (buf.size() < 20) return Result<void>{"TrustStore::load: file too small"};
    if (std::memcmp(buf.data(), "NNTS", 4) != 0)
        return Result<void>{"TrustStore::load: bad magic"};
    uint32_t version = readU32LE(buf.data() + 4);
    if (version != 1) return Result<void>{"TrustStore::load: unsupported version"};
    int64_t  ts      = readI64LE(buf.data() + 8);
    uint32_t count   = readU32LE(buf.data() + 16);

    size_t cursor = 20;
    std::vector<CaEntry> loaded;
    for (uint32_t i = 0; i < count; ++i) {
        if (cursor + 8 > buf.size()) return Result<void>{"TrustStore: parse error (entry header)"};
        auto levelU = readU32LE(buf.data() + cursor); cursor += 4;
        auto cerLen = readU32LE(buf.data() + cursor); cursor += 4;
        if (cursor + cerLen > buf.size()) return Result<void>{"TrustStore: parse error (cert data)"};

        CaEntry e;
        e.level   = static_cast<TrustLevel>(levelU);
        e.derCert.assign(buf.data() + cursor, buf.data() + cursor + cerLen);
        cursor += cerLen;

        // Extract subject DN via OpenSSL
        const uint8_t* cp = e.derCert.data();
        X509* cert = d2i_X509(nullptr, &cp, static_cast<long>(e.derCert.size()));
        if (!cert) return Result<void>{"TrustStore::load: invalid DER cert"};
        char dnBuf[512] = {};
        X509_NAME_oneline(X509_get_subject_name(cert), dnBuf, sizeof(dnBuf));
        X509_free(cert);
        e.subjectDN = dnBuf;
        loaded.push_back(std::move(e));
    }

    // TODO: verify store signature against embedded root CA public key
    // For Phase 2 we skip signature verification of the store itself;
    // the TUP mechanism handles trust store updates with full verification.

    entries_      = std::move(loaded);
    creationTime_ = ts;
    return Result<void>{};
}

// ─── save ─────────────────────────────────────────────────────────────────────

Result<void> TrustStore::save(std::string_view path) const {
    // Serialise entries
    std::vector<uint8_t> buf;
    // Reserve space for header: "NNTS" + version + timestamp + count
    buf.resize(20);
    std::memcpy(buf.data(), "NNTS", 4);
    writeU32LE(buf.data() + 4, 1);
    int64_t now = static_cast<int64_t>(std::time(nullptr));
    writeI64LE(buf.data() + 8, now);
    writeU32LE(buf.data() + 16, static_cast<uint32_t>(entries_.size()));

    for (const auto& e : entries_) {
        size_t pos = buf.size();
        buf.resize(pos + 8 + e.derCert.size());
        writeU32LE(buf.data() + pos,     static_cast<uint32_t>(e.level));
        writeU32LE(buf.data() + pos + 4, static_cast<uint32_t>(e.derCert.size()));
        std::memcpy(buf.data() + pos + 8, e.derCert.data(), e.derCert.size());
    }

    // TODO: sign buf with root CA private key and append signature.
    // Phase 2: write unsigned (test mode). Production: sign via nnstudio-sign.
    uint32_t sigLen = 0;
    buf.resize(buf.size() + 4 + sigLen);
    writeU32LE(buf.data() + buf.size() - 4, sigLen);

    std::ofstream f(std::string{path}, std::ios::binary | std::ios::trunc);
    if (!f.is_open()) return Result<void>{"TrustStore::save: cannot open file for writing"};
    f.write(reinterpret_cast<const char*>(buf.data()),
            static_cast<std::streamsize>(buf.size()));
    if (!f) return Result<void>{"TrustStore::save: write error"};
    return Result<void>{};
}

// ─── createDefault ────────────────────────────────────────────────────────────

TrustStore TrustStore::createDefault() {
    TrustStore s;
    s.creationTime_ = static_cast<int64_t>(std::time(nullptr));
    // No CAs loaded by default — TrustUpdateHandler adds them via TUPs.
    // The root CA public key is embedded in kRootCaPubKeyDer but is used only
    // for verification, not as a CA entry (it is implicit in all verifications).
    (void)kRootCaPubKeyDerLen; // suppress unused-variable warning
    return s;
}

} // namespace trust
} // namespace nnstudio
